# Generated by Django 2.2.5 on 2019-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190927_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gost',
        ),
        migrations.DeleteModel(
            name='tost',
        ),
    ]
