# Generated by Django 3.1.1 on 2020-09-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_customuser_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
